#!/usr/bin/env bash
# by Ereptor, Plenteum

HASH=$1

curl --silent 'http://block-explorer.plenteum.com/daemon/json_rpc' --data '{"jsonrpc":"2.0","id":"test","method":"f_transaction_json","params":{"hash":"'"$HASH"'"}}' --compressed | jq '.result.tx.extra' | xxd -r -p













